name: Scheduled Maintenance

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  maintenance-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run maintenance script
        run: |
          chmod +x ./maintenance-script.sh
          ./maintenance-script.sh
